language: python
python:
  - "2.7"
  - "3.6"
before_script:
  - pip install -U pip
  - pip install -e .
  - pip install -e .[test]
script: 
  - py.test src/ --cov=src/ --cov-report=src/
after_success:
  - coveralls